<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <AssemblyName>ERechnung.VirtualPrinter.Tasks</AssemblyName>
    <TargetPlatformMinVersion>10.0.26100.0</TargetPlatformMinVersion>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <Platforms>x64;ARM64</Platforms>
    <UseWinUI>true</UseWinUI>
    <CsWinRTComponent>true</CsWinRTComponent>
    <CsWinRTWindowsMetadata>10.0.26100.0</CsWinRTWindowsMetadata>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.3.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../PrintCore/PrintCore.csproj" />
  </ItemGroup>
</Project>
