LangString addOrReinstall ${LANG_GERMAN} "Programm ergänzen oder erneut installieren"
LangString alreadyInstalled ${LANG_GERMAN} "Bereits installiert"
LangString alreadyInstalledLong ${LANG_GERMAN} "${PRODUCTNAME} ${VERSION} ist bereits installiert. Wählen Sie den gewünschten Vorgang aus und klicken Sie auf Weiter."
LangString appRunning ${LANG_GERMAN} "{{product_name}} ist noch geöffnet. Bitte schließen Sie das Programm und versuchen Sie es erneut."
LangString appRunningOkKill ${LANG_GERMAN} "{{product_name}} ist noch geöffnet. Klicken Sie auf OK, um das Programm zu schließen."
LangString chooseMaintenanceOption ${LANG_GERMAN} "Was möchten Sie tun?"
LangString choowHowToInstall ${LANG_GERMAN} "Wie möchten Sie ${PRODUCTNAME} installieren?"
LangString createDesktop ${LANG_GERMAN} "Verknüpfung auf dem Schreibtisch erstellen"
LangString dontUninstall ${LANG_GERMAN} "Nicht entfernen"
LangString dontUninstallDowngrade ${LANG_GERMAN} "Nicht entfernen"
LangString failedToKillApp ${LANG_GERMAN} "Das Programm konnte nicht geschlossen werden. Bitte schließen Sie es selbst und versuchen Sie es erneut."
LangString installingWebview2 ${LANG_GERMAN} "Eine benötigte Windows-Komponente wird eingerichtet …"
LangString newerVersionInstalled ${LANG_GERMAN} "Eine neuere Version von ${PRODUCTNAME} ist bereits installiert. Bitte behalten Sie die neuere Version."
LangString älter ${LANG_GERMAN} "ältere"
LangString olderOrUnknownVersionInstalled ${LANG_GERMAN} "Eine $R4-Version von ${PRODUCTNAME} ist bereits installiert. Sie können sie vor der neuen Installation entfernen."
LangString silentDowngrades ${LANG_GERMAN} "Diese ältere Version kann nicht automatisch installiert werden. Bitte starten Sie die Installationsdatei von Hand."
LangString unableToUninstall ${LANG_GERMAN} "Das Programm konnte nicht entfernt werden."
LangString uninstallApp ${LANG_GERMAN} "${PRODUCTNAME} entfernen"
LangString uninstallBeforeInstalling ${LANG_GERMAN} "Vorherige Version entfernen"
LangString unbekannt ${LANG_GERMAN} "unbekannte"
LangString webview2AbortError ${LANG_GERMAN} "Eine benötigte Windows-Komponente konnte nicht eingerichtet werden. Bitte starten Sie die Installation erneut."
LangString webview2DownloadError ${LANG_GERMAN} "Eine benötigte Windows-Komponente konnte nicht heruntergeladen werden. Bitte prüfen Sie Ihre Internetverbindung."
LangString webview2DownloadSuccess ${LANG_GERMAN} "Die benötigte Windows-Komponente wurde heruntergeladen."
LangString webview2Downloading ${LANG_GERMAN} "Eine benötigte Windows-Komponente wird heruntergeladen …"
LangString webview2InstallError ${LANG_GERMAN} "Eine benötigte Windows-Komponente konnte nicht eingerichtet werden."
LangString webview2InstallSuccess ${LANG_GERMAN} "Die benötigte Windows-Komponente wurde eingerichtet."
LangString deleteAppData ${LANG_GERMAN} "Gespeicherte Einstellungen löschen"
