import { assertValidEn16931Invoice } from "../domain/validate.js";
import type { CalculatedInvoice, Party } from "../domain/types.js";
import { compactDate, element as e, XML_HEADER } from "./xml.js";

// ZUGFeRD 2.5.x / Factur-X 1.09.x EN 16931 profile identifier.
export const ZUGFERD_EN16931_GUIDELINE = "urn:cen.eu:en16931:2017";

function partyXml(tag: string, party: Party): string {
  const tax = party.vatId ? `<ram:SpecifiedTaxRegistration>${e("ram:ID", party.vatId, ' schemeID="VA"')}</ram:SpecifiedTaxRegistration>` : "";
  const contact = party.contact ? `<ram:DefinedTradeContact>${e("ram:PersonName", party.contact.name)}${party.contact.phone ? `<ram:TelephoneUniversalCommunication>${e("ram:CompleteNumber", party.contact.phone)}</ram:TelephoneUniversalCommunication>` : ""}${party.contact.email ? `<ram:EmailURIUniversalCommunication>${e("ram:URIID", party.contact.email)}</ram:EmailURIUniversalCommunication>` : ""}</ram:DefinedTradeContact>` : "";
  return `<ram:${tag}>${e("ram:Name", party.name)}${contact}<ram:PostalTradeAddress>${e("ram:PostcodeCode", party.address.postalCode)}${e("ram:LineOne", party.address.line1)}${e("ram:LineTwo", party.address.line2)}${e("ram:CityName", party.address.city)}${e("ram:CountryID", party.address.countryCode)}</ram:PostalTradeAddress>${tax}</ram:${tag}>`;
}

export function generateCii(invoice: CalculatedInvoice): string {
  assertValidEn16931Invoice(invoice);
  const lines = invoice.calculatedLines.map((line) => `<ram:IncludedSupplyChainTradeLineItem><ram:AssociatedDocumentLineDocument>${e("ram:LineID", line.id)}</ram:AssociatedDocumentLineDocument><ram:SpecifiedTradeProduct>${e("ram:Name", line.name)}${e("ram:Description", line.description)}</ram:SpecifiedTradeProduct><ram:SpecifiedLineTradeAgreement><ram:NetPriceProductTradePrice>${e("ram:ChargeAmount", line.netUnitPrice)}</ram:NetPriceProductTradePrice></ram:SpecifiedLineTradeAgreement><ram:SpecifiedLineTradeDelivery>${e("ram:BilledQuantity", line.quantity, ` unitCode="${line.unitCode}"`)}</ram:SpecifiedLineTradeDelivery><ram:SpecifiedLineTradeSettlement><ram:ApplicableTradeTax>${e("ram:TypeCode", "VAT")}${e("ram:CategoryCode", line.tax.categoryCode)}${e("ram:RateApplicablePercent", line.tax.rate)}</ram:ApplicableTradeTax><ram:SpecifiedTradeSettlementLineMonetarySummation>${e("ram:LineTotalAmount", line.netAmount)}</ram:SpecifiedTradeSettlementLineMonetarySummation></ram:SpecifiedLineTradeSettlement></ram:IncludedSupplyChainTradeLineItem>`).join("");
  const taxes = invoice.taxes.map((tax) => `<ram:ApplicableTradeTax>${e("ram:CalculatedAmount", tax.taxAmount)}${e("ram:TypeCode", "VAT")}${e("ram:ExemptionReason", tax.exemptionReason)}${e("ram:BasisAmount", tax.taxableAmount)}${e("ram:CategoryCode", tax.categoryCode)}${e("ram:RateApplicablePercent", tax.rate)}</ram:ApplicableTradeTax>`).join("");
  const payment = `<ram:SpecifiedTradeSettlementPaymentMeans>${e("ram:TypeCode", invoice.payment.meansCode)}${invoice.payment.iban ? `<ram:PayeePartyCreditorFinancialAccount>${e("ram:IBANID", invoice.payment.iban)}${e("ram:AccountName", invoice.payment.accountName)}</ram:PayeePartyCreditorFinancialAccount>` : ""}${invoice.payment.bic ? `<ram:PayeeSpecifiedCreditorFinancialInstitution>${e("ram:BICID", invoice.payment.bic)}</ram:PayeeSpecifiedCreditorFinancialInstitution>` : ""}</ram:SpecifiedTradeSettlementPaymentMeans>`;
  return `${XML_HEADER}<rsm:CrossIndustryInvoice xmlns:rsm="urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100" xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:100"><rsm:ExchangedDocumentContext><ram:GuidelineSpecifiedDocumentContextParameter>${e("ram:ID", ZUGFERD_EN16931_GUIDELINE)}</ram:GuidelineSpecifiedDocumentContextParameter></rsm:ExchangedDocumentContext><rsm:ExchangedDocument>${e("ram:ID", invoice.invoiceNumber)}${e("ram:TypeCode", invoice.invoiceType)}<ram:IssueDateTime>${e("udt:DateTimeString", compactDate(invoice.issueDate), ' format="102"')}</ram:IssueDateTime>${invoice.notes?.map((note) => `<ram:IncludedNote>${e("ram:Content", note)}</ram:IncludedNote>`).join("") ?? ""}</rsm:ExchangedDocument><rsm:SupplyChainTradeTransaction>${lines}<ram:ApplicableHeaderTradeAgreement>${e("ram:BuyerReference", invoice.buyerReference || undefined)}${partyXml("SellerTradeParty", invoice.seller)}${partyXml("BuyerTradeParty", invoice.buyer)}</ram:ApplicableHeaderTradeAgreement><ram:ApplicableHeaderTradeDelivery>${invoice.serviceDate ? `<ram:ActualDeliverySupplyChainEvent><ram:OccurrenceDateTime>${e("udt:DateTimeString", compactDate(invoice.serviceDate), ' format="102"')}</ram:OccurrenceDateTime></ram:ActualDeliverySupplyChainEvent>` : ""}</ram:ApplicableHeaderTradeDelivery><ram:ApplicableHeaderTradeSettlement>${e("ram:InvoiceCurrencyCode", invoice.currency)}${payment}${taxes}${invoice.payment.terms || invoice.dueDate ? `<ram:SpecifiedTradePaymentTerms>${e("ram:Description", invoice.payment.terms)}${invoice.dueDate ? `<ram:DueDateDateTime>${e("udt:DateTimeString", compactDate(invoice.dueDate), ' format="102"')}</ram:DueDateDateTime>` : ""}</ram:SpecifiedTradePaymentTerms>` : ""}<ram:SpecifiedTradeSettlementHeaderMonetarySummation>${e("ram:LineTotalAmount", invoice.totals.lineNet)}${e("ram:TaxBasisTotalAmount", invoice.totals.taxExclusive)}${e("ram:TaxTotalAmount", invoice.totals.taxTotal, ` currencyID="${invoice.currency}"`)}${e("ram:GrandTotalAmount", invoice.totals.taxInclusive)}${e("ram:DuePayableAmount", invoice.totals.payable)}</ram:SpecifiedTradeSettlementHeaderMonetarySummation></ram:ApplicableHeaderTradeSettlement></rsm:SupplyChainTradeTransaction></rsm:CrossIndustryInvoice>`;
}
