import { assertValidInvoice } from "../domain/validate.js";
import type { CalculatedInvoice, Party } from "../domain/types.js";
import { element as e, XML_HEADER } from "./xml.js";

export const XRECHNUNG_CUSTOMIZATION_ID = "urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0";
export const XRECHNUNG_PROFILE_ID = "urn:fdc:peppol.eu:2017:poacc:billing:01:1.0";

function partyXml(wrapper: string, party: Party): string {
  const endpoint = party.electronicAddress ? e("cbc:EndpointID", party.electronicAddress.value, ` schemeID="${party.electronicAddress.schemeId}"`) : "";
  const contact = party.contact ? `<cac:Contact>${e("cbc:Name", party.contact.name)}${e("cbc:Telephone", party.contact.phone)}${e("cbc:ElectronicMail", party.contact.email)}</cac:Contact>` : "";
  return `<cac:${wrapper}><cac:Party>${endpoint}<cac:PartyName>${e("cbc:Name", party.name)}</cac:PartyName><cac:PostalAddress>${e("cbc:StreetName", party.address.line1)}${e("cbc:AdditionalStreetName", party.address.line2)}${e("cbc:CityName", party.address.city)}${e("cbc:PostalZone", party.address.postalCode)}<cac:Country>${e("cbc:IdentificationCode", party.address.countryCode)}</cac:Country></cac:PostalAddress>${party.vatId ? `<cac:PartyTaxScheme>${e("cbc:CompanyID", party.vatId)}<cac:TaxScheme>${e("cbc:ID", "VAT")}</cac:TaxScheme></cac:PartyTaxScheme>` : ""}<cac:PartyLegalEntity>${e("cbc:RegistrationName", party.name)}</cac:PartyLegalEntity>${contact}</cac:Party></cac:${wrapper}>`;
}

export function generateUbl(invoice: CalculatedInvoice): string {
  assertValidInvoice(invoice);
  const c = invoice.currency;
  const taxes = invoice.taxes.map((tax) => `<cac:TaxSubtotal>${e("cbc:TaxableAmount", tax.taxableAmount, ` currencyID="${c}"`)}${e("cbc:TaxAmount", tax.taxAmount, ` currencyID="${c}"`)}<cac:TaxCategory>${e("cbc:ID", tax.categoryCode)}${e("cbc:Percent", tax.rate)}${e("cbc:TaxExemptionReason", tax.exemptionReason)}<cac:TaxScheme>${e("cbc:ID", "VAT")}</cac:TaxScheme></cac:TaxCategory></cac:TaxSubtotal>`).join("");
  const lines = invoice.calculatedLines.map((line) => `<cac:InvoiceLine>${e("cbc:ID", line.id)}${e("cbc:InvoicedQuantity", line.quantity, ` unitCode="${line.unitCode}"`)}${e("cbc:LineExtensionAmount", line.netAmount, ` currencyID="${c}"`)}<cac:Item>${e("cbc:Description", line.description)}${e("cbc:Name", line.name)}<cac:ClassifiedTaxCategory>${e("cbc:ID", line.tax.categoryCode)}${e("cbc:Percent", line.tax.rate)}<cac:TaxScheme>${e("cbc:ID", "VAT")}</cac:TaxScheme></cac:ClassifiedTaxCategory></cac:Item><cac:Price>${e("cbc:PriceAmount", line.netUnitPrice, ` currencyID="${c}"`)}${e("cbc:BaseQuantity", "1", ` unitCode="${line.unitCode}"`)}</cac:Price></cac:InvoiceLine>`).join("");
  return `${XML_HEADER}<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2">${e("cbc:CustomizationID", XRECHNUNG_CUSTOMIZATION_ID)}${e("cbc:ProfileID", XRECHNUNG_PROFILE_ID)}${e("cbc:ID", invoice.invoiceNumber)}${e("cbc:IssueDate", invoice.issueDate)}${e("cbc:DueDate", invoice.dueDate)}${e("cbc:InvoiceTypeCode", invoice.invoiceType)}${invoice.notes?.map((note) => e("cbc:Note", note)).join("") ?? ""}${e("cbc:DocumentCurrencyCode", c)}${e("cbc:BuyerReference", invoice.buyerReference)}${partyXml("AccountingSupplierParty", invoice.seller)}${partyXml("AccountingCustomerParty", invoice.buyer)}${invoice.serviceDate ? `<cac:Delivery>${e("cbc:ActualDeliveryDate", invoice.serviceDate)}</cac:Delivery>` : ""}${invoice.payment.iban ? `<cac:PaymentMeans>${e("cbc:PaymentMeansCode", invoice.payment.meansCode)}${e("cbc:PaymentID", invoice.payment.paymentReference)}<cac:PayeeFinancialAccount>${e("cbc:ID", invoice.payment.iban)}${e("cbc:Name", invoice.payment.accountName)}${invoice.payment.bic ? `<cac:FinancialInstitutionBranch>${e("cbc:ID", invoice.payment.bic)}</cac:FinancialInstitutionBranch>` : ""}</cac:PayeeFinancialAccount></cac:PaymentMeans>` : ""}${invoice.payment.terms ? `<cac:PaymentTerms>${e("cbc:Note", invoice.payment.terms)}</cac:PaymentTerms>` : ""}<cac:TaxTotal>${e("cbc:TaxAmount", invoice.totals.taxTotal, ` currencyID="${c}"`)}${taxes}</cac:TaxTotal><cac:LegalMonetaryTotal>${e("cbc:LineExtensionAmount", invoice.totals.lineNet, ` currencyID="${c}"`)}${e("cbc:TaxExclusiveAmount", invoice.totals.taxExclusive, ` currencyID="${c}"`)}${e("cbc:TaxInclusiveAmount", invoice.totals.taxInclusive, ` currencyID="${c}"`)}${e("cbc:PayableAmount", invoice.totals.payable, ` currencyID="${c}"`)}</cac:LegalMonetaryTotal>${lines}</Invoice>`;
}
